version: "1"
rules:
  - base: swiftwasm
    upstream: swift/main
    mergeMethod: merge
  - base: swift/main
    upstream: apple:swift/main
    mergeMethod: hardreset
  - base: swift/release/5.3
    upstream: apple:swift/release/5.3
    mergeMethod: hardreset
  - base: swiftwasm-release/5.3
    upstream: swift/release/5.3
    mergeMethod: merge
  - base: swift/release/5.4
    upstream: apple:swift/release/5.4
    mergeMethod: hardreset
  - base: swiftwasm-release/5.4
    upstream: swift/release/5.4
    mergeMethod: merge
  - base: swift/release/5.5
    upstream: apple:swift/release/5.5
    mergeMethod: hardreset
  - base: swiftwasm-release/5.5
    upstream: swift/release/5.5
    mergeMethod: merge
label: ":arrow_heading_down: Upstream Tracking"
